### ISSUE TITLE
Corrupt data

### ISSUE THREAD

**Issue by honzasladek** [contember/admin#24]
Admin says `PersistError Error: Corrupt data: undefined alias for node with index 0.`. 

**Steps to reproduce:**
1. Go here: https://contember.mgw.cz/p/demo/live/locale=cs/home-page
2. Enter something in field "Nadpis (nad čárkou)"
3. Try saving
-> in console you'll the error above.

The API correctly returns that the slug is not unique:
(`Execution has failed:\nlocales.0.link.url: UniqueConstraintViolation (Value (\"/\") of unique constraint (url) already exists`)

**Comment by VojtaStanek** [comment]
This is fixed (cannot reproduce).
