### ISSUE TITLE
Paragraph styling disappear when dragged in BlockEditor

### ISSUE THREAD

**Issue by jonasNobile** [contember/admin#270]
### Case
Drag paragraph in `<BlockEditor />`

### Example

Dragging second paragraph

![Screenshot 2022-04-14 at 14 04 04](https://user-images.githubusercontent.com/47249487/163387453-d2f271e5-35fc-4938-bde9-296068ac6c8d.png)

**Comment by attitude** [comment]
Unable to replicate, seems to be already fixed. Feel free to reopen.
