### ISSUE TITLE
Red star marking the element required is not visible on text field

### ISSUE THREAD

**Issue by Thommas2316** [contember/admin#381]
Hello,

I've come across an "aesthetic" bug 🐞. When you set `required` prop on `TextField` it will not propagate the prop downstream from `SimpleRelativeSingleFieldProxy` to `FieldContainer`.
Below I attach screenshots documenting the component tree, set props and render of given component.

Stack:
NodeJS: v16.16.0
NPM: 8.11.0
Packages:
```
├── @contember/admin-i18n@1.1.0-alpha.6
├── @contember/admin@1.1.0-alpha.6
├── @contember/schema-definition@1.0.0-rc.16
├── @contember/schema@1.0.0-rc.16
├── @sentry/browser@6.19.7
├── @sentry/integrations@6.19.7
├── @types/react@17.0.47
├── eslint-config-next@12.2.2
├── eslint@8.20.0
├── react-dom@17.0.2
├── react@17.0.2
├── typescript@4.7.4
└── vite@2.9.14
```

#### The `SimpleRelativeSingleFieldProxy` has `required` prop and it is set to `true`
![The SimpleRelativeSingleFieldProxy has required prop and it is set to true](https://user-images.githubusercontent.com/3959662/179509045-566bb0ad-7ab8-4245-94f2-b613c613f8cb.png)

#### The nested `FieldContainer` is missing the `required` prop
![The nested FieldContainer is missing the required prop](https://user-images.githubusercontent.com/3959662/179509105-06b4cfba-3651-4454-bbd1-5e5b156b2877.png)

#### The span that should contain the asterisk is rendered correctly, but without the * symbol
![The span that should contain the asterisk is rendered correctly, but without the * symbol](https://user-images.githubusercontent.com/3959662/179509210-7bf758fa-1219-4ccf-9a5b-38d36613efcf.png)

#### Rendered `TextField` component
![Rendered TextField component](https://user-images.githubusercontent.com/3959662/179509246-6b9b17c9-0dae-4cb8-b1da-1030903a3606.png)

#### Field definition in code
![Field definition in code](https://user-images.githubusercontent.com/3959662/179510971-ef3f3b45-b406-4690-9be0-e04e9d0c7d53.png)

I hope I did not miss anything obvious and that I provided you with everything you need to take a look into it.

Thank you for your time and for this wonderful project.

Best regards,
Tom

**Comment by honzasladek** [comment]
Thanks for the report @Thommas2316! It's fixed in https://github.com/contember/admin/releases/tag/v1.1.0-alpha.7
